# Generated by Django 4.2.2 on 2023-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
