# Generated by Django 4.2.2 on 2023-06-27 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_equipment_type_alter_port_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='opposite_side',
        ),
        migrations.AlterField(
            model_name='connection',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='line', to='register.port', unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='station', to='register.port', unique=True),
        ),
    ]
