# Generated by Django 4.2.2 on 2023-06-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_port_opposite_side_alter_connection_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='line', to='register.port'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='station', to='register.port'),
        ),
    ]
