# Generated by Django 4.2.2 on 2023-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_rename_equipment_id_port_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('E', 'equipment'), ('O', 'optical frame'), ('F', 'electrical frame'), ('V', 'virtual object'), ('-', 'other')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='port',
            name='media_type',
            field=models.CharField(choices=[('E', 'electrical'), ('O', 'optical'), ('V', 'virtual')], default='E', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='communication',
            unique_together={('name', 'direction_from', 'direction_to', 'consumer')},
        ),
    ]
