# Generated by Django 4.2.2 on 2023-06-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_equipment_type_alter_port_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='connect', to='register.port'),
        ),
    ]
