# Generated by Django 4.2.2 on 2023-06-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_connection_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connect',
        ),
    ]
