# Generated by Django 4.2.2 on 2023-07-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_connection_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ports', to='register.equipment'),
        ),
        migrations.AlterField(
            model_name='port',
            name='port_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
