# Generated by Django 4.2.2 on 2023-07-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_port_connected_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='connected_ports', to='register.communication'),
        ),
    ]
