# Generated by Django 4.2.2 on 2023-07-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_port_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ports', to='register.communication'),
        ),
        migrations.AlterField(
            model_name='port',
            name='connected_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='connected_from', to='register.port'),
        ),
    ]
