# Generated by Django 4.2.2 on 2023-08-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_port_communication_alter_port_connected_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='equipment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='register.equipment'),
        ),
    ]
