# Generated by Django 4.2.2 on 2023-08-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_port_equipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('port_name', 'equipment')},
        ),
    ]
