# Generated by Django 4.2.2 on 2023-08-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_port_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('name', 'code')},
        ),
    ]
