# Generated by Django 4.2.2 on 2023-08-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_alter_port_port_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='endpoint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='equipments', to='register.endpoint'),
        ),
    ]
