# Generated by Django 4.2.2 on 2023-08-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_equipment_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('name', 'endpoint')},
        ),
    ]
