# Generated by Django 4.2.2 on 2023-08-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_alter_consumer_name_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='communication_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='register.interfacetype'),
        ),
    ]
