# Generated by Django 4.2.4 on 2023-08-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_communication_communication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='endpoint_opposite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='systems', to='register.endpoint'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
