# Generated by Django 4.2.4 on 2023-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_alter_endpoint_unique_together_alter_endpoint_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
