# Generated by Django 4.2.4 on 2023-09-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_alter_communication_direction_from_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communication',
            unique_together={('name', 'direction_from', 'direction_to', 'consumer', 'communication_type')},
        ),
    ]
